# Generated by Django 6.0.3 on 2026-03-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='exp_type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Summer Training', 'Summer Training')], max_length=50),
        ),
    ]
